apiVersion: organizations.aws.m.upbound.io/v1beta1
kind: OrganizationalUnit
metadata:
  name: ou-environments
  namespace: crossplane-system
spec:
  forProvider:
    name: Environments
    parentId: r-xxxx
    tags:
      ManagedBy: crossplane
  providerConfigRef:
    name: main
    kind: ProviderConfig